"""
StateWeave Auto-Instrumentation — One line, zero code changes.
=================================================================
Like Sentry's `sentry_sdk.init()`, this auto-instruments your agents
with state versioning, confidence alerting, and crash recovery.

Usage::

    import stateweave
    stateweave.auto()

    # That's it. Your agents now have:
    # - Auto-checkpoint on configurable triggers
    # - Confidence drift alerts
    # - Crash recovery via stateweave rollback
    # - Replay/why/compare available on all checkpointed state

Advanced::

    stateweave.auto(
        checkpoint_every=3,       # every 3 steps (default: 5)
        alert_on_confidence=0.5,  # alert when confidence drops below this
        store_dir="./checkpoints",  # custom store location
        frameworks=["langgraph"],   # only instrument specific frameworks
        verbose=True,               # print to stdout on each checkpoint
    )
"""

import atexit
import logging
from dataclasses import dataclass
from typing import Dict, List, Optional

from stateweave.middleware.auto_checkpoint import CheckpointMiddleware, CheckpointStrategy
from stateweave.schema.v1 import StateWeavePayload

logger = logging.getLogger("stateweave.auto")


@dataclass
class Alert:
    """An alert generated by auto-instrumentation."""

    agent_id: str
    alert_type: str  # confidence_drop, hallucination_risk, large_state_change, crash
    message: str
    version: int
    severity: str = "warning"  # info, warning, critical


@dataclass
class AutoConfig:
    """Configuration for auto-instrumentation."""

    checkpoint_every: int = 5
    strategy: str = "every_n_steps"
    delta_threshold: int = 3
    alert_on_confidence: float = 0.5
    store_dir: Optional[str] = None
    frameworks: Optional[List[str]] = None  # None = all detected
    verbose: bool = False
    alert_callback: Optional[object] = None  # Callable[[Alert], None]


class AutoInstrumentor:
    """Core auto-instrumentation engine.

    Manages per-agent middleware instances, generates alerts,
    and provides a unified interface for recording agent state.

    This is the singleton managed by `stateweave.auto()`.
    """

    def __init__(self, config: AutoConfig):
        self.config = config
        self._agents: Dict[str, CheckpointMiddleware] = {}
        self._alerts: List[Alert] = []
        self._enabled = True
        self._prev_confidence: Dict[str, float] = {}

    def record(
        self,
        payload: StateWeavePayload,
        agent_id: Optional[str] = None,
        force: bool = False,
    ) -> bool:
        """Record an agent state update.

        Auto-creates middleware for new agents, auto-checkpoints based
        on configured strategy, and generates alerts.

        Args:
            payload: Current agent state.
            agent_id: Agent identifier (defaults to payload.metadata.agent_id).
            force: Force a checkpoint regardless of strategy.

        Returns:
            True if a checkpoint was created.
        """
        if not self._enabled:
            return False

        agent_id = agent_id or payload.metadata.agent_id

        # Get or create middleware for this agent
        if agent_id not in self._agents:
            self._agents[agent_id] = CheckpointMiddleware(
                agent_id=agent_id,
                every_n_steps=self.config.checkpoint_every,
                store_dir=self.config.store_dir,
                strategy=CheckpointStrategy(self.config.strategy),
                delta_threshold=self.config.delta_threshold,
                label_prefix="auto",
            )

        mw = self._agents[agent_id]

        # Check for alerts before recording
        self._check_alerts(agent_id, payload, mw)

        # Record (auto-checkpoint based on strategy)
        did_checkpoint = mw.record(payload, force=force)

        if did_checkpoint and self.config.verbose:
            v = mw.checkpoint_count
            print(
                f"  🧶 [stateweave] Checkpointed {agent_id} v{v}"
                f" ({mw.step_count} steps, {mw.checkpoint_overhead_ms:.0f}ms avg)"
            )

        return did_checkpoint

    def _check_alerts(
        self,
        agent_id: str,
        payload: StateWeavePayload,
        mw: CheckpointMiddleware,
    ) -> None:
        """Generate alerts for anomalous state."""
        wm = payload.cognitive_state.working_memory

        # Check confidence
        confidence = None
        for key in ("confidence", "confidence_score", "agent_confidence"):
            if key in wm:
                try:
                    confidence = float(wm[key])
                except (ValueError, TypeError):
                    pass
                break

        if confidence is not None:
            prev_conf = self._prev_confidence.get(agent_id)

            # Low confidence alert
            if confidence < self.config.alert_on_confidence:
                alert = Alert(
                    agent_id=agent_id,
                    alert_type="confidence_drop",
                    message=(
                        f"Confidence {confidence:.2f} below threshold"
                        f" {self.config.alert_on_confidence}"
                    ),
                    version=mw.step_count,
                    severity="warning",
                )
                self._alerts.append(alert)
                self._fire_alert(alert)

            # Sudden drop alert
            if prev_conf is not None and (prev_conf - confidence) > 0.3:
                pct = int((prev_conf - confidence) / prev_conf * 100) if prev_conf > 0 else 0
                alert = Alert(
                    agent_id=agent_id,
                    alert_type="confidence_drop",
                    message=f"Confidence dropped {pct}% ({prev_conf:.2f} → {confidence:.2f})",
                    version=mw.step_count,
                    severity="critical",
                )
                self._alerts.append(alert)
                self._fire_alert(alert)

            self._prev_confidence[agent_id] = confidence

        # Check for hallucination risk
        if "hallucination_risk" in wm:
            risk_val = str(wm["hallucination_risk"]).upper()
            if risk_val in ("HIGH", "CRITICAL", "TRUE"):
                alert = Alert(
                    agent_id=agent_id,
                    alert_type="hallucination_risk",
                    message=f"Hallucination risk: {risk_val}",
                    version=mw.step_count,
                    severity="critical",
                )
                self._alerts.append(alert)
                self._fire_alert(alert)

    def _fire_alert(self, alert: Alert) -> None:
        """Emit an alert."""
        if self.config.verbose:
            icon = "🔴" if alert.severity == "critical" else "⚠"
            print(f"  {icon} [stateweave] {alert.agent_id}: {alert.message}")

        if self.config.alert_callback and callable(self.config.alert_callback):
            self.config.alert_callback(alert)

        logger.warning(
            f"stateweave.alert.{alert.alert_type}",
            extra={
                "agent_id": alert.agent_id,
                "severity": alert.severity,
                "alert_message": alert.message,
            },
        )

    @property
    def alerts(self) -> List[Alert]:
        """All alerts generated since initialization."""
        return list(self._alerts)

    @property
    def agents(self) -> Dict[str, CheckpointMiddleware]:
        """All tracked agents and their middleware."""
        return dict(self._agents)

    def summary(self) -> Dict:
        """Return a summary of auto-instrumentation state."""
        return {
            "enabled": self._enabled,
            "agents": {
                aid: {
                    "steps": mw.step_count,
                    "checkpoints": mw.checkpoint_count,
                    "avg_overhead_ms": round(mw.checkpoint_overhead_ms, 2),
                }
                for aid, mw in self._agents.items()
            },
            "total_alerts": len(self._alerts),
            "config": {
                "checkpoint_every": self.config.checkpoint_every,
                "strategy": self.config.strategy,
                "alert_on_confidence": self.config.alert_on_confidence,
            },
        }

    def disable(self) -> None:
        """Disable auto-instrumentation."""
        self._enabled = False

    def enable(self) -> None:
        """Re-enable auto-instrumentation."""
        self._enabled = True


# ── Global singleton ──

_instrumentor: Optional[AutoInstrumentor] = None


def auto(
    checkpoint_every: int = 5,
    strategy: str = "every_n_steps",
    delta_threshold: int = 3,
    alert_on_confidence: float = 0.5,
    store_dir: Optional[str] = None,
    frameworks: Optional[List[str]] = None,
    verbose: bool = False,
    alert_callback: Optional[object] = None,
) -> AutoInstrumentor:
    """Enable StateWeave auto-instrumentation. One line, zero code changes.

    Call this once at the top of your script. StateWeave will auto-checkpoint
    agent state based on your configured strategy and alert on anomalies.

    Args:
        checkpoint_every: Checkpoint frequency (for every_n_steps strategy).
        strategy: "every_n_steps", "on_significant_delta", or "manual_only".
        delta_threshold: Min changes to trigger checkpoint (delta strategy).
        alert_on_confidence: Alert when agent confidence drops below this.
        store_dir: Checkpoint storage directory.
        frameworks: Only instrument these frameworks (None = all).
        verbose: Print to stdout on each checkpoint and alert.
        alert_callback: Optional callback function for alerts.

    Returns:
        The AutoInstrumentor singleton.

    Example::

        import stateweave
        sw = stateweave.auto(verbose=True)

        # Later, record agent state:
        sw.record(payload)

        # Or use in a loop:
        for step in agent.run():
            payload = adapter.export_state(agent_id)
            sw.record(payload)
    """
    global _instrumentor

    config = AutoConfig(
        checkpoint_every=checkpoint_every,
        strategy=strategy,
        delta_threshold=delta_threshold,
        alert_on_confidence=alert_on_confidence,
        store_dir=store_dir,
        frameworks=frameworks,
        verbose=verbose,
        alert_callback=alert_callback,
    )

    _instrumentor = AutoInstrumentor(config)

    if verbose:
        import stateweave as sw

        print(f"  🧶 StateWeave v{sw.__version__} auto-instrumentation enabled")
        print(
            f"     Strategy: {strategy}"
            f" | Checkpoint every: {checkpoint_every}"
            f" | Alert threshold: {alert_on_confidence}"
        )

    # Register cleanup on exit
    atexit.register(_cleanup)

    logger.info(
        "StateWeave auto-instrumentation enabled",
        extra={"strategy": strategy, "checkpoint_every": checkpoint_every},
    )

    return _instrumentor


def get_instrumentor() -> Optional[AutoInstrumentor]:
    """Get the global AutoInstrumentor. Returns None if auto() hasn't been called."""
    return _instrumentor


def _cleanup() -> None:
    """Cleanup handler registered with atexit — prints rich session summary card."""
    global _instrumentor
    if _instrumentor and _instrumentor.config.verbose:
        import time

        summary = _instrumentor.summary()
        agents = summary["agents"]
        if agents:
            total_steps = sum(a["steps"] for a in agents.values())
            total_cps = sum(a["checkpoints"] for a in agents.values())
            total_alerts = summary["total_alerts"]

            print()
            print("  ┌──────────────────────────────────────────────┐")
            print("  │  🧶 StateWeave Session Summary               │")
            print("  ├──────────────────────────────────────────────┤")

            for aid, stats in agents.items():
                print(f"  │  Agent: {aid:<37s}│")
                print(f"  │    Steps: {stats['steps']:<10d} Checkpoints: {stats['checkpoints']:<8d}│")

                # Show confidence trend if available
                if aid in _instrumentor._prev_confidence:
                    conf = _instrumentor._prev_confidence[aid]
                    conf_str = f"{conf:.0%}"
                    # Try to find initial confidence
                    initial_confs = [
                        a for a in _instrumentor._alerts
                        if a.agent_id == aid and "→" in a.message
                    ]
                    if initial_confs:
                        conf_str = initial_confs[-1].message.split("(")[-1].rstrip(")")
                    arrow = "▲" if conf >= 0.7 else "▼" if conf < 0.5 else "─"
                    print(f"  │    Confidence: {conf_str:<10s} {arrow:<25s}│")

                avg = stats["avg_overhead_ms"]
                print(f"  │    Overhead: {avg:.1f}ms avg per checkpoint{' ' * max(0, 13 - len(f'{avg:.1f}'))}│")

            print("  ├──────────────────────────────────────────────┤")
            if total_alerts > 0:
                print(f"  │  ⚠️  {total_alerts} alert(s) — run: stateweave why <agent>  │")
            else:
                print("  │  ✅ No alerts — agent ran clean               │")
            print(f"  │  💡 Run: stateweave report                    │")
            print("  └──────────────────────────────────────────────┘")
            print()
    _instrumentor = None

