"""
StateWeave shell completions — generate bash/zsh/fish completion scripts.

Usage:
    stateweave completions bash > ~/.stateweave-completions.bash
    stateweave completions zsh > ~/.stateweave-completions.zsh
    stateweave completions fish > ~/.config/fish/completions/stateweave.fish
"""


COMMANDS = [
    "adapters", "benchmark", "blame", "checkpoint", "ci", "compare",
    "detect", "diff", "doctor", "export", "generate-adapter", "history",
    "import", "init", "inspect", "log", "migrate", "pop", "quickstart",
    "replay", "rollback", "scan", "schema", "stash", "stats", "status",
    "try", "validate", "version", "watch", "why",
]

FRAMEWORKS = [
    "autogen", "crewai", "dspy", "haystack", "langgraph",
    "letta", "llamaindex", "mcp", "openai_agents", "semantic_kernel",
]


def generate_bash():
    """Generate bash completion script."""
    commands_str = " ".join(COMMANDS)
    frameworks_str = " ".join(FRAMEWORKS)
    return f'''# StateWeave bash completion — generated by stateweave completions bash
_stateweave() {{
    local cur prev commands frameworks
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    commands="{commands_str}"
    frameworks="{frameworks_str}"

    case "${{prev}}" in
        stateweave)
            COMPREPLY=( $(compgen -W "${{commands}}" -- "${{cur}}") )
            return 0
            ;;
        --from|--to|-f|--framework)
            COMPREPLY=( $(compgen -W "${{frameworks}}" -- "${{cur}}") )
            return 0
            ;;
        inspect|validate|detect|diff|checkpoint)
            COMPREPLY=( $(compgen -f -- "${{cur}}") )
            return 0
            ;;
    esac

    if [[ "${{cur}}" == -* ]]; then
        COMPREPLY=( $(compgen -W "--help --output --encrypt --verbose" -- "${{cur}}") )
        return 0
    fi
}}
complete -F _stateweave stateweave
'''


def generate_zsh():
    """Generate zsh completion script."""
    commands_str = " ".join(COMMANDS)
    frameworks_str = " ".join(FRAMEWORKS)
    return f'''#compdef stateweave
# StateWeave zsh completion — generated by stateweave completions zsh

_stateweave() {{
    local -a commands frameworks
    commands=({commands_str})
    frameworks=({frameworks_str})

    _arguments \\
        '1:command:((${{commands}}))' \\
        '--from[Source framework]:framework:((${{frameworks}}))' \\
        '--to[Target framework]:framework:((${{frameworks}}))' \\
        '-f[Framework]:framework:((${{frameworks}}))' \\
        '--framework[Framework]:framework:((${{frameworks}}))' \\
        '--output[Output file]:file:_files' \\
        '-o[Output file]:file:_files' \\
        '--encrypt[Enable encryption]' \\
        '--verbose[Verbose output]' \\
        '*:file:_files'
}}

_stateweave "$@"
'''


def generate_fish():
    """Generate fish completion script."""
    lines = ["# StateWeave fish completion — generated by stateweave completions fish"]
    lines.append("# Clear existing completions")
    lines.append("complete -c stateweave -e")
    lines.append("")

    for cmd in COMMANDS:
        lines.append(f"complete -c stateweave -f -n '__fish_use_subcommand' -a '{cmd}'")

    lines.append("")
    lines.append("# Framework completions for --from/--to")
    for fw in FRAMEWORKS:
        lines.append(
            f"complete -c stateweave -n '__fish_seen_subcommand_from migrate' "
            f"-l from -a '{fw}'"
        )
        lines.append(
            f"complete -c stateweave -n '__fish_seen_subcommand_from migrate' "
            f"-l to -a '{fw}'"
        )

    return "\n".join(lines) + "\n"
"""

def generate(shell):
    if shell == "bash":
        return generate_bash()
    elif shell == "zsh":
        return generate_zsh()
    elif shell == "fish":
        return generate_fish()
    else:
        raise ValueError(f"Unknown shell: {shell}. Supported: bash, zsh, fish")
"""
